### ISSUE TITLE
Criar componente de cadastro de turma

### ISSUE THREAD

**Issue by Junior-Shyko** [Junior-Shyko/react-with-docker#1]

**Comment by Junior-Shyko** [comment]
Criado

**Comment by JuinEsp** [comment]
### Rodar vendor do compose
 #### Acessa o container com o comando
      `docker exec -it phpturma bash`
 #### Depois roda o composer com o seguinte comando
      `composer install`
#### Deve criar um arquivo .env
#### Depois deve rodar o seguinte comando
     ` docker-compose exec php-fpm php artisan key:generate`
